name: tapway
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  tabler_icons: ^2.3.0

  # Logger & Utilities
  logger: ^2.0.2
  logging: ^1.2.0
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.10+1
  path_provider: ^2.1.4
  path: ^1.9.0
  image_picker: ^1.1.2

  # Firebase (latest compatible with Flutter 3.8)
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.2.1
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3
  firebase_storage: ^12.3.4

  # State Management & DI
  get: ^4.6.6
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7

  # Location Services
  geolocator: ^13.0.2
  geocoding: ^4.0.0

  # Map
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  flutter_map_tile_caching: ^10.1.1
  flutter_map_marker_cluster: ^8.1.0

  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Permissions
  permission_handler: ^11.3.1

  # Accessibility
  flutter_tts: ^4.0.2
  speech_to_text: ^7.0.0

  # Notifications
  flutter_local_notifications: ^17.2.3

  # Form Validation
  form_validator: ^2.1.1

  # UI / Icons
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
