// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp9Sciww6pvV_9ZDDBLFU7E3PYxdbjqf8',
    appId: '1:12852607486:web:ec0029b327cc8f0fc728af',
    messagingSenderId: '12852607486',
    projectId: 'tapway-emergency',
    authDomain: 'tapway-emergency.firebaseapp.com',
    storageBucket: 'tapway-emergency.firebasestorage.app',
    measurementId: 'G-DLZKXBRQB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmJbDCUvVh2I1A2KWpdNTCWLbH1iX_XzM',
    appId: '1:12852607486:android:d6db3567e3992e0ec728af',
    messagingSenderId: '12852607486',
    projectId: 'tapway-emergency',
    storageBucket: 'tapway-emergency.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp9Sciww6pvV_9ZDDBLFU7E3PYxdbjqf8',
    appId: '1:12852607486:web:4c567976974f213ac728af',
    messagingSenderId: '12852607486',
    projectId: 'tapway-emergency',
    authDomain: 'tapway-emergency.firebaseapp.com',
    storageBucket: 'tapway-emergency.firebasestorage.app',
    measurementId: 'G-HFGQ1SNCSQ',
  );
}
